version: "3"

volumes:
  polar:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/evanfeenstra/.polar/networks/1/volumes/lnd

# networks:
#   my-network:
#     driver_opts:
#       com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
#     ipam:
#       config:
#         - subnet: "127.0.0.1/16"

services:
  bitcoind:
    image: ruimarinho/bitcoin-core:0.21.1
    restart: on-failure
    container_name: bitcoin-server
    volumes:
      - ./bitcoind-data/.bitcoin:/home/bitcoin/.bitcoin
    command: -printtoconsole
      -regtest=1
      -server=1
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -txindex=1
      -fallbackfee=0.0002
      -rpcauth='foo:7d9ba5ae63c3d4dc30583ff4fe65a67e$$9e3634e81c11659e3de036d0bf88f89cd169c1039e6e09607562d54765c649cc'
      -zmqpubhashblock=tcp://host.docker.internal:28332
      -zmqpubhashtx=tcp://host.docker.internal:28333
    ports:
      - 18443:18443
      - 18444:18444
      - 28332:28332
      - 28333:28333

  alice-lnd:
    image: lnzap/lnd:latest
    container_name: alice-lnd
    volumes:
      - ./lnd-data/alice:/lnd
    ports:
      - 9735:9735
      - 127.0.0.1:10009:10009
    command: --bitcoin.active
      --bitcoin.regtest
      --debuglevel=info
      --rpclisten=0.0.0.0:10009
      --accept-keysend
      --alias=alice-lnd
      --bitcoin.node=bitcoind
      --bitcoin.defaultchanconfs=2
      --bitcoind.rpcuser=foo
      --bitcoind.rpcpass=7d9ba5ae63c3d4dc30583ff4fe65a67e$$9e3634e81c11659e3de036d0bf88f89cd169c1039e6e09607562d54765c649cc
      --bitcoind.zmqpubrawblock=tcp://host.docker.internal:28332
      --bitcoind.zmqpubrawtx=tcp://host.docker.internal:28333

  # lndsetup:
  #   image: node:12-buster-slim
  #   depends_on:
  #     - alice-lnd
  #   restart: "no"
  #   working_dir: "/lndsetup/"
  #   entrypoint: ["/lndsetup/entrypoint.sh"]
  #   volumes:
  #     - ./lnd-data/alice:/alice-lnd
  #     - ./lndsetup:/lndsetup

  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=sphinx
      - POSTGRES_USER=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432

  tribes:
    image: sphinxlightning/sphinx-tribes
    restart: on-failure
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:sphinx@host.docker.internal:5433/postgres?sslmode=disable
    ports:
      - 5002:5002

  auth:
    image: sphinxlightning/sphinx-auth
    restart: on-failure
    depends_on:
      - db
    environment:
      - JWT_KEY=19e0bb49bhyuibme
      - HOST=localhost:9090
    ports:
      - 9090:9090

  mqtt:
    image: sphinxlightning/sphinx-mqtt
    restart: on-failure
    depends_on:
      - auth
    ports:
      - 1883:1883

  meme:
    image: sphinxlightning/sphinx-meme
    restart: on-failure
    depends_on:
      - db
    environment:
      - JWT_KEY=19e0bb49bhyuibme
      - STORAGE_MODE=local
      - LOCAL_DIR=files
      - LOCAL_ENCRYPTION_KEY=88303a55f5829d9e35936364204bcb007fe330db649902fa1085a7bce3732347
      - HOST=localhost:5000
      - DATABASE_URL=postgres://postgres:sphinx@host.docker.internal:5433/postgres?sslmode=disable
    ports:
      - 5000:5000

  alice:
    image: sphinx-relay
    restart: on-failure
    entrypoint:
      [
        "node",
        "/relay/dist/app.js",
        "--config=/relay/relayconfigs/alice.json",
        "--db=/relay/relayconfigs/alice-db.json",
      ]
    volumes:
      - ./relayconfigs:/relay/relayconfigs
      - polar:/relay/.polar/networks/1/volumes/lnd
    environment:
      - NODE_ENV=development
      - PORT=3001
      - LND_IP=host.docker.internal
    ports:
      - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  relaysetup:
    image: node:12-buster-slim
    depends_on:
      - alice
    restart: "no"
    entrypoint: ["node", "/relayconfigs/setup/index.js"]
    volumes:
      - ./relayconfigs:/relayconfigs
