version: "3"

services:

  bitcoind:
    image: lncm/bitcoind:v0.21.1
    restart: on-failure
    container_name: bitcoind.sphinx
    volumes:
      - ./bitcoind:/data/.bitcoin
    ports:
      - 8332:8332
      - 8333:8333
      - 28332:28332
      - 28333:28333
      - 18443:18443

  alice-lnd:
    image: lnzap/lnd:latest
    container_name: alice-lnd.sphinx
    volumes:
      - ./lnd/alice:/lnd
      - ./lndsetup:/lndsetup
    ports:
      - 9735:9735
      - 10009:10009
      - 38881:38881
    command: --configfile=/lndsetup/alice.conf

  lndsetup:
    image: node:12-buster-slim
    depends_on:
      - alice-lnd
    restart: "no"
    entrypoint: ["node", "/lndsetup/index.js"]
    volumes:
      - ./lnd/alice:/alice
      - ./lndsetup:/lndsetup

  db:
    image: postgres
    container_name: db.sphinx
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=sphinx
      - POSTGRES_USER=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432

  tribes:
    image: sphinxlightning/sphinx-tribes
    container_name: tribes.sphinx
    restart: on-failure
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:sphinx@db.sphinx:5432/postgres?sslmode=disable
    ports:
      - 5002:5002
      - 13007:5002
      - 13000:5002

  auth:
    image: sphinxlightning/sphinx-auth
    container_name: auth.sphinx
    restart: on-failure
    depends_on:
      - db
    environment:
      - JWT_KEY=19e0bb49bhyuibme
      - HOST=localhost:9090
    ports:
      - 9090:9090

  mqtt:
    image: sphinxlightning/sphinx-mqtt
    container_name: mqtt.sphinx
    restart: on-failure
    depends_on:
      - auth
    ports:
      - 1883:1883

  meme:
    image: sphinxlightning/sphinx-meme
    container_name: meme.sphinx
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./memes:/app/files
    environment:
      - PORT=5555
      - JWT_KEY=19e0bb49bhyuibme
      - STORAGE_MODE=local
      - LOCAL_DIR=files
      - LOCAL_ENCRYPTION_KEY=88303a55f5829d9e35936364204bcb007fe330db649902fa1085a7bce3732347
      - HOST=localhost:5555
      - DATABASE_URL=postgres://postgres:sphinx@db.sphinx:5432/postgres?sslmode=disable
    ports:
      - 5555:5555

  alice:
    image: sphinxlightning/sphinx-relay-test
    container_name: alice.sphinx
    restart: on-failure
    depends_on:
      - alice-lnd
    entrypoint:
      [
        "node",
        "/relay/dist/app.js",
        "--config=/relay/relayconfigs/alice.json",
        "--db=/relay/relayconfigs/alice-db.json",
      ]
    volumes:
      - ./relayconfigs:/relay/relayconfigs
      - ./lnd/alice:/relay/alice
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - 3001:3001

  relaysetup:
    image: node:12-buster-slim
    depends_on:
      - alice
    restart: "no"
    entrypoint: ["node", "/relayconfigs/setup/index.js"]
    volumes:
      - ./relayconfigs:/relayconfigs
