version: "3"

services:
  exampleBot:
    image: node:12-buster-slim 
    container_name: example-bot-sphinx
    restart: always 
    working_dir: "/example_bot"
    command:
      - /bin/sh
      - -c
      - |
              npm install
              npm install -g nodemon
              node ./isEnvAvailible.js && nodemon --legacy-watch --watch index.js --exec 'npm run build && npm run start'
    volumes:
      - ../relay/botEnvVars.json:/example_bot/botEnvVars.json  
      - ../botSandBox/sphinx-example-bot/:/example_bot/
      - ../botSandBox/isEnvAvailible.js:/example_bot/isEnvAvailible.js
    environment:
      - IS_SPHINX_STACK=true
      - CHOKIDAR_USEPOLLING=true
      - SPHINX_INDEX=0 
    ports:
      - 3333:3333  

  BetBot:
    image: node:12-buster-slim 
    container_name: bet-bot-sphinx
    restart: always 
    working_dir: "/example_bot"
    command:
      - /bin/sh
      - -c
      - |
              npm install
              npm install -g nodemon
              ls
              node ./isEnvAvailible.js && nodemon --legacy-watch --watch "src/**" --ext "ts,json,js" --exec 'npm run build && npm run start'
    volumes:
      - ../relay/botEnvVars.json:/example_bot/botEnvVars.json  
      - ../botSandBox/sphinx-betting-bot/:/example_bot/
      - ../botSandBox/isEnvAvailible.js:/example_bot/isEnvAvailible.js
    environment:
      - IS_SPHINX_STACK=true
      - CHOKIDAR_USEPOLLING=true
      - SPHINX_INDEX=1 
      - REDIS_URL=redis://db.bettingBot:6379
      - FLUSH_ALL=1
    ports:
      - 3334:3334

  redis:
    image: redis:alpine
    container_name: db.bettingBot
    command: redis-server --appendonly yes
    ports:
      - 6379:6379  
    volumes:
        - ./redisData/data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

